@Restaurants.API_HostAddress = https://localhost:7044

@token = CfDJ8E5rXAed1p5GlMjv8Z3RzWWwVNBE9nRW3650Skf1bQ_8b-a_G2LY52m7rEGpH0AJ6xcx94kQ4P2tlHXSTerlUZvBmMbdZBvDIqvhLmOLoltKYvM2nTmwGQPcgL8LY6suYKF2cp4syhLZVOL-GUKCanB24YU2DcodNowzNTQo8DrgYfAb7TvY7nN4Um2QGJkuY2Z7DlHnPVbrsNYnuOqFshHOv-KvNVMJxu-I_wiRsxxB-6Jlodf9EPNYGwldwQ_LDGylMX_icSlQF1rjWl7xbZWgjmP-m-Nu-mb36KNIgqDAnu_bmbI107I3ueW2VcWnIOunw6pjR8Z60IwW3Ca_P-zYX-z4_MZvPMxeDdYI9JcZCH_9HI-wma3Xs-q7zvtoUZA2yXox0rP0KHWNYPtIx5C4aVR1Ehi4E25Q_2jg4J3nTfsKoYsc8z4upi12Cf31LQnvydKZG_D5UjxBepxEzA-Ky4Qmgl1MUUlJtYH5BC-fO2FpYqV3G_KhV1hmP3RfnWIHT0F3PPoX5uKppyXQWwsmsPOuG5gVRiXhLqSwjFzNp55GyzBVL6YjrR0irRYb0HVJ1IqmV6T-sAqXmNmdy9GDDrJG38sbb_ob_0XRoU5qDfkOnZBK2AyucLjEG5WDAu9OFbCRoDTYNhJhxcDqLh-vXznTaHqK3zns0m72Mk6L9SD5VR9Bnzf0fei_2k6W5g

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3
Authorization : Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization : Bearer {{token}}
Content-Type: application/json

{
    "Name": "Goli Badapav11",
    "Description": "Authentic Mumbai dish with fresh ingredients.",
    "Category": "Indian",
    "HasDelivery": true,
    "ContactEmail": "contact@mumbaiGoli.com",
    "ContactNumber": "9949677777",
    "City": "San Francisco",
    "Street": "Market Street",
    "PostalCode": "94-103"
}

###

@id=10
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###
@id = 3
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Content-Type: application/json

{
 "Name": "Lutf cafe",
    "Description": "Authentic Lucknow dish with fresh ingredients.",
    "HasDelivery": false
}

###
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
    "email":"user@test.com",
    "password":"Testpassword1!"
}
###
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
    "email":"Admin@test.com",
    "password":"Testpassword1!"
}
